name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  Deploy-development:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - uses: actions/checkout@v2

    # Install Node.js
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'

    # Install npm dependencies
    - name: Install dependencies
      run: npm install

    # Install Vercel CLI
    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    # Pull Vercel Environment Information
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}

    # Build Project Artifacts
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

    # Deploy Project Artifacts to Vercel
    - name: Deploy Project Artifacts to Vercel
      run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --project=${{ secrets.VERCEL_PROJECT_ID }} --org=${{ secrets.VERCEL_ORG_ID_SANITIZED }}
